// <auto-generated />
using System;
using ContabOne.Api.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContabOne.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContabOne.Api.Domain.Agente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiKeyPrefixo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EscritorioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoContatoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VersaoAgente")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash");

                    b.HasIndex("EscritorioId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Agentes");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EscritorioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severidade")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EscritorioId", "ResolvidoEm")
                        .HasFilter("\"ResolvidoEm\" IS NULL");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ApuracaoSegregacao", b =>
                {
                    b.Property<Guid>("ApuracaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<decimal>("Receita")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ApuracaoId", "Categoria");

                    b.ToTable("ApuracaoSegregacoes");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ApuracaoSimples", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cofins")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Competencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Csll")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Das")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("EditadoManualmente")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EscritorioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Faturamento")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Icms")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool?>("Impedido")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ImportadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Inss")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Ipi")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Irpj")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Iss")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Pis")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Rba")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("SemMovimento")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Sublimite")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EscritorioId", "ClienteId", "Competencia")
                        .IsUnique();

                    b.ToTable("ApuracoesSimples");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CertificadoNomeArquivo")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("CertificadoValidade")
                        .HasColumnType("date");

                    b.Property<string>("CnpjHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CnpjMascarado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EscritorioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PrimeiraVezVistoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EscritorioId", "Codigo")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ConfiguracaoEscritorio", b =>
                {
                    b.Property<Guid>("EscritorioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Chave")
                        .HasColumnType("text");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EscritorioId", "ProdutoId", "Chave");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ConfiguracoesEscritorio");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Dominio", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("Icone")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Codigo");

                    b.ToTable("Dominios");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Escritorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CnpjHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CnpjMascarado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PlanoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CnpjHash")
                        .IsUnique();

                    b.HasIndex("PlanoId");

                    b.ToTable("Escritorios");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.EscritorioProduto", b =>
                {
                    b.Property<Guid>("EscritorioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DesabilitadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HabilitadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EscritorioId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("EscritorioProdutos");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Execucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EscritorioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VersaoAgente")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("EscritorioId", "IniciadoEm")
                        .IsDescending(false, true);

                    b.ToTable("Execucoes");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ExecucaoMetrica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Competencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DuracaoMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ExecucaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("QtdBaixadas")
                        .HasColumnType("integer");

                    b.Property<int>("QtdFalhas")
                        .HasColumnType("integer");

                    b.Property<int>("QtdPuladas")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExecucaoId");

                    b.HasIndex("ClienteId", "Competencia");

                    b.ToTable("ExecucaoMetricas");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaxAgentes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxClientes")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PermiteEmitidas")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecoMensal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DominioCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Paginas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("TemAgente")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("DominioCodigo");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ReceitaMensalCliente", b =>
                {
                    b.Property<Guid>("EscritorioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Competencia")
                        .HasColumnType("text");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrigemCompetencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ReceitaBruta")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("EscritorioId", "ClienteId", "Competencia");

                    b.HasIndex("ClienteId");

                    b.ToTable("ReceitasMensaisCliente");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.RegraColeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("PublicadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Versao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Versao")
                        .IsUnique();

                    b.ToTable("RegraColetas");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.TourPaginaVista", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Pagina")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("VistoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsuarioId", "Pagina");

                    b.ToTable("TourPaginasVistas");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("DeveTrocarSenha")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Papel")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UltimoLoginEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ContabOne.Api.Domain.UsuarioEscritorio", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EscritorioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsuarioId", "EscritorioId");

                    b.HasIndex("EscritorioId");

                    b.ToTable("UsuariosEscritorios");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Agente", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Escritorio", "Escritorio")
                        .WithMany("Agentes")
                        .HasForeignKey("EscritorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabOne.Api.Domain.Produto", "Produto")
                        .WithMany("Agentes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Escritorio");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Alerta", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("ContabOne.Api.Domain.Escritorio", "Escritorio")
                        .WithMany("Alertas")
                        .HasForeignKey("EscritorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Escritorio");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ApuracaoSegregacao", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.ApuracaoSimples", "Apuracao")
                        .WithMany("Segregacoes")
                        .HasForeignKey("ApuracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apuracao");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ApuracaoSimples", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabOne.Api.Domain.Escritorio", "Escritorio")
                        .WithMany()
                        .HasForeignKey("EscritorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Escritorio");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Cliente", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Escritorio", "Escritorio")
                        .WithMany("Clientes")
                        .HasForeignKey("EscritorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escritorio");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ConfiguracaoEscritorio", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Escritorio", "Escritorio")
                        .WithMany("Configuracoes")
                        .HasForeignKey("EscritorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabOne.Api.Domain.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Escritorio");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Escritorio", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Plano", "Plano")
                        .WithMany("Escritorios")
                        .HasForeignKey("PlanoId");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.EscritorioProduto", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Escritorio", "Escritorio")
                        .WithMany("Produtos")
                        .HasForeignKey("EscritorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabOne.Api.Domain.Produto", "Produto")
                        .WithMany("Escritorios")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Escritorio");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Execucao", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Agente", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabOne.Api.Domain.Escritorio", "Escritorio")
                        .WithMany("Execucoes")
                        .HasForeignKey("EscritorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Escritorio");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ExecucaoMetrica", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabOne.Api.Domain.Execucao", "Execucao")
                        .WithMany("Metricas")
                        .HasForeignKey("ExecucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Execucao");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Produto", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Dominio", "Dominio")
                        .WithMany("Produtos")
                        .HasForeignKey("DominioCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dominio");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ReceitaMensalCliente", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabOne.Api.Domain.Escritorio", "Escritorio")
                        .WithMany()
                        .HasForeignKey("EscritorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Escritorio");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.TourPaginaVista", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.UsuarioEscritorio", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Escritorio", "Escritorio")
                        .WithMany("Usuarios")
                        .HasForeignKey("EscritorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabOne.Api.Domain.Usuario", "Usuario")
                        .WithMany("Escritorios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escritorio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContabOne.Api.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ContabOne.Api.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContabOne.Api.Domain.ApuracaoSimples", b =>
                {
                    b.Navigation("Segregacoes");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Dominio", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Escritorio", b =>
                {
                    b.Navigation("Agentes");

                    b.Navigation("Alertas");

                    b.Navigation("Clientes");

                    b.Navigation("Configuracoes");

                    b.Navigation("Execucoes");

                    b.Navigation("Produtos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Execucao", b =>
                {
                    b.Navigation("Metricas");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Plano", b =>
                {
                    b.Navigation("Escritorios");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Produto", b =>
                {
                    b.Navigation("Agentes");

                    b.Navigation("Escritorios");
                });

            modelBuilder.Entity("ContabOne.Api.Domain.Usuario", b =>
                {
                    b.Navigation("Escritorios");
                });
#pragma warning restore 612, 618
        }
    }
}
